project:
  type: website
  output-dir: "docs"

website:
  title: ""
  navbar:
    search: TRUE
    logo: images/CNC_Logo2.avif
    left:
      - href: index.qmd
        text: Home
      - href: inat.qmd
        text: Participate
      - about.qmd

format:
  html:
    theme: custom
    css: styles.css
    toc: true

editor: visual

