project:
  type: website
  output-dir: "docs"


website:
  title: ""
  navbar:
    search: TRUE
    logo: images/CNC_Logo2.avif
    right:
      - href: index.qmd
        text: Home
      - href: participate.qmd
        text: Participate
      - href: events.qmd
        text: Events
      - href: Past_Years.qmd
        text: Past Years
      - href: Partnerships.qmd
        text: Partnerships
format:
  html:
    theme: custom
    css: styles.css
    toc: true

editor: visual
execute:
  echo: false
  warning: false
  message: false
  
  
