---
title: "Events"
---

Click on an event to learn more/RSVP

\*denotes limited attendances on a first come first serve basis

+-----------+-----------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------+--------------------------------+
| Time      | April 25                                                                                                                          | April 26                                                                                                                    | April 27                                                                                                     | April 28                       |
+===========+===================================================================================================================================+=============================================================================================================================+==============================================================================================================+================================+
| 8 am      | [Dead River March Bird Walk](https://maps.app.goo.gl/yq2DzznVVNeUYSuS8)                                                           | [Harlow Lake Bird Walk](https://docs.google.com/forms/d/1btoqABcI3UWkH9Uik6yDnR4ycvx8tkL9SOTrFdNBGwo/edit)                  | BLP Bird Walk                                                                                                | Wright St. Falls Bird Walk     |
+-----------+-----------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------+--------------------------------+
| 9:30 am   |                                                                                                                                   |                                                                                                                             | Wetmore Bog Biodiversity Bonanza                                                                             |                                |
+-----------+-----------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------+--------------------------------+
| 10 am     |                                                                                                                                   | -   [Harlow Aquatic Invertebrates](https://docs.google.com/forms/d/1X1wirTngXfwcKPtso14FqbWyAIX1NyOBlZYED_EfTwU/edit)       |                                                                                                              | Harlow Lake Mammals and Tracks |
|           |                                                                                                                                   |                                                                                                                             |                                                                                                              |                                |
|           |                                                                                                                                   | -   [Moosewood Nature Center](https://docs.google.com/forms/d/1oSqQFwsVKF_o3r9wirs8FSDnbAWCsS4DV64SQupe6To/edit)            |                                                                                                              |                                |
+-----------+-----------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------+--------------------------------+
| 11 am     |                                                                                                                                   | -   [Harlow Lake Plants, Fungi, Lichens](https://docs.google.com/forms/d/1gWEb7z3D7Arhgn5Z7-kWevSeWIamsn_yBW7RCx53DJU/edit) | [Compeau Creek Hawk Walk](https://docs.google.com/forms/d/1dAtrM89hO13Ii-xvDZ7LQNn9_2FVDateHqTv8ZlaLhw/edit) |                                |
|           |                                                                                                                                   |                                                                                                                             |                                                                                                              |                                |
|           |                                                                                                                                   | -   [Moosewood Nature Center](https://docs.google.com/forms/d/1oSqQFwsVKF_o3r9wirs8FSDnbAWCsS4DV64SQupe6To/edit)            |                                                                                                              |                                |
+-----------+-----------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------+--------------------------------+
| 12 pm     |                                                                                                                                   | [Moosewood Nature Center](https://docs.google.com/forms/d/1oSqQFwsVKF_o3r9wirs8FSDnbAWCsS4DV64SQupe6To/edit)                | [Compeau Creek Hawk Walk](https://docs.google.com/forms/d/1dAtrM89hO13Ii-xvDZ7LQNn9_2FVDateHqTv8ZlaLhw/edit) |                                |
+-----------+-----------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------+--------------------------------+
| 1 pm      |                                                                                                                                   | [Moosewood Nature Center](https://docs.google.com/forms/d/1oSqQFwsVKF_o3r9wirs8FSDnbAWCsS4DV64SQupe6To/edit)                |                                                                                                              | NMU Campus Clean up            |
+-----------+-----------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------+--------------------------------+
| 2 pm      | [Multiple Events: Click here to find out more](https://docs.google.com/forms/d/172UOaekcNfUY4Mj_42pLiy9rHGzHBWCNuO6j4GnQ0zo/edit) |                                                                                                                             |                                                                                                              |                                |
+-----------+-----------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------+--------------------------------+
| 3 pm      | [Multiple Events: Click here to find out more](https://docs.google.com/forms/d/172UOaekcNfUY4Mj_42pLiy9rHGzHBWCNuO6j4GnQ0zo/edit) |                                                                                                                             | [Dead River Aquatic Invertebrates](https://maps.app.goo.gl/3rnaLB1oUWEGPKqn9)                                |                                |
+-----------+-----------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------+--------------------------------+
| 4 pm      | [Multiple Events: Click here to find out more](https://docs.google.com/forms/d/172UOaekcNfUY4Mj_42pLiy9rHGzHBWCNuO6j4GnQ0zo/edit) |                                                                                                                             | Dead River Aquatic Invertebrates                                                                             |                                |
+-----------+-----------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------+--------------------------------+
| 5 pm      |                                                                                                                                   |                                                                                                                             |                                                                                                              |                                |
+-----------+-----------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------+--------------------------------+
| 6 pm      |                                                                                                                                   |                                                                                                                             |                                                                                                              |                                |
+-----------+-----------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------+--------------------------------+
| 7 pm      |                                                                                                                                   |                                                                                                                             |                                                                                                              |                                |
+-----------+-----------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------+--------------------------------+
| 8 pm      | [Moosewood Nighttime ecology](https://docs.google.com/forms/d/1-sdPIkZcoI2bFehFNnfNPGrWTPhhZQt3v4YFZDNqhQI/edit)                  |                                                                                                                             | Beaver Grove Recreation Area Woodcock walk                                                                   |                                |
+-----------+-----------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------+--------------------------------+
