---
title: "Join Us!"
format: html
editor: visual
---

## How to Participate:

1.  **Create an [iNaturalist account](https://www.inaturalist.org/signup) (if you do not have one already)**
2.  **Join the [Marquette City Nature Challenge Project](https://www.inaturalist.org/projects/city-nature-challenge-2025-marquette-mi)**
3.  **Record photos or audio of wild organisms in Marquette County during the observation period (April 25-28th)**
4.  **Upload to iNaturalist via the app or website Repeat steps 2-3 (and attend group observation events!\*)**

## New to iNaturalist?

[Click here](https://inaturalist.freshdesk.com/en/support/solutions/folders/151000552105) to get started!

## Volunteer!

Do you have experience with identifying organisms in nature? Come help teach others how to use iNaturalist and make quality observations! Please contact organizers Owen VanAntwerpen (ovanantw\@nmu.edu) and Mattea Muscat (mmuscat\@nmu.edu).

## Host an Event

Interested in hosting an event as an organization? Please contact organizers Owen VanAntwerpen (ovanantw\@nmu.edu) and Mattea Muscat (mmuscat\@nmu.edu).
